spring:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      jdbc:
        time_zone: UTC
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    password: workflow
    username: workflow
    url: jdbc:postgresql://localhost:5432/workflow
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  batch:
    jdbc:
      initialize-schema: always
  sql:
    init:
      mode: always